services:
  db:
    image: "postgres:latest"
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5434
    volumes:
      - postgres-data:/var/lib/postgresql/data

  migrations:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    command: poetry run alembic upgrade head

  tests:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    command: poetry run pytest Test/ -v -s

volumes:
  postgres-data:
