"""empty message

Revision ID: 896ebb62979d
Revises: 
Create Date: 2025-10-19 20:37:10.504429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896ebb62979d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('detail_for_bicycle_detail_id_fkey', 'detail_for_bicycle', type_='foreignkey')
    op.drop_constraint('detail_for_bicycle_bicycle_id_fkey', 'detail_for_bicycle', type_='foreignkey')
    op.create_foreign_key(None, 'detail_for_bicycle', 'bicycle', ['bicycle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'detail_for_bicycle', 'detail', ['detail_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('rent_book_bicycle_id_fkey', 'rent_book', type_='foreignkey')
    op.drop_constraint('rent_book_client_id_fkey', 'rent_book', type_='foreignkey')
    op.drop_constraint('rent_book_staff_id_fkey', 'rent_book', type_='foreignkey')
    op.create_foreign_key(None, 'rent_book', 'staff', ['staff_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rent_book', 'bicycle', ['bicycle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rent_book', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('service_book_bicycle_id_fkey', 'service_book', type_='foreignkey')
    op.drop_constraint('service_book_staff_id_fkey', 'service_book', type_='foreignkey')
    op.drop_constraint('service_book_detail_id_fkey', 'service_book', type_='foreignkey')
    op.create_foreign_key(None, 'service_book', 'detail', ['detail_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'service_book', 'staff', ['staff_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'service_book', 'bicycle', ['bicycle_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_book', type_='foreignkey')
    op.drop_constraint(None, 'service_book', type_='foreignkey')
    op.drop_constraint(None, 'service_book', type_='foreignkey')
    op.create_foreign_key('service_book_detail_id_fkey', 'service_book', 'detail', ['detail_id'], ['id'])
    op.create_foreign_key('service_book_staff_id_fkey', 'service_book', 'staff', ['staff_id'], ['id'])
    op.create_foreign_key('service_book_bicycle_id_fkey', 'service_book', 'bicycle', ['bicycle_id'], ['id'])
    op.drop_constraint(None, 'rent_book', type_='foreignkey')
    op.drop_constraint(None, 'rent_book', type_='foreignkey')
    op.drop_constraint(None, 'rent_book', type_='foreignkey')
    op.create_foreign_key('rent_book_staff_id_fkey', 'rent_book', 'staff', ['staff_id'], ['id'])
    op.create_foreign_key('rent_book_client_id_fkey', 'rent_book', 'client', ['client_id'], ['id'])
    op.create_foreign_key('rent_book_bicycle_id_fkey', 'rent_book', 'bicycle', ['bicycle_id'], ['id'])
    op.drop_constraint(None, 'detail_for_bicycle', type_='foreignkey')
    op.drop_constraint(None, 'detail_for_bicycle', type_='foreignkey')
    op.create_foreign_key('detail_for_bicycle_bicycle_id_fkey', 'detail_for_bicycle', 'bicycle', ['bicycle_id'], ['id'])
    op.create_foreign_key('detail_for_bicycle_detail_id_fkey', 'detail_for_bicycle', 'detail', ['detail_id'], ['id'])
    # ### end Alembic commands ###
